services:
  edocument-app:
    image: edocument-app
    build:
      context: .
    ports:
      - "127.0.0.1:3001:3000"
    restart: unless-stopped # Restart policy
    networks:
      - networkedoc

networks:
  networkedoc:
    driver: bridge